name: wflow
description: A Flutter application for student or freelancer and business connected, in addition the application provide solusion commit two hand when create contract for working
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_config_plus: ^1.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  dio: ^5.3.2
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  google_sign_in: ^6.1.4
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  local_auth: ^2.1.6
  flutter_flipperkit: ^0.0.29
  shared_preferences: ^2.2.0
  hydrated_bloc: ^9.1.2
  introduction_screen: ^3.1.11
  flutter_localization: ^0.1.13
  json_annotation: ^4.8.1
  emoji_picker_flutter: ^1.6.1
  voice_message_package: ^1.0.41
  flutter_sound: ^9.2.13
  intl: any
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  socket_io_client: ^2.0.3
  file_picker: ^5.3.3
  camera: ^0.10.5+4
  freezed_annotation: ^2.4.1
  badges: ^3.1.2
  url_launcher: ^6.1.14
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  logger: ^1.4.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    - assets/languages/
    - assets/anim/
    - assets/icons/bottom/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Light.otf
