name: wflow
description: A Flutter application for student or freelancer and business connected, in addition the application provide solusion commit two hand when create contract for working
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_config_plus: ^1.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  dio: ^5.3.2
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  google_sign_in: ^6.1.4
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  local_auth: ^2.1.6
  flutter_flipperkit: ^0.0.29
  shared_preferences: ^2.2.0
  hydrated_bloc: ^9.1.2
  introduction_screen: ^3.1.11
  flutter_localization: ^0.1.13
  json_annotation: ^4.8.1
  emoji_picker_flutter: ^1.6.1
  voice_message_package: ^1.0.41
  flutter_sound: ^9.2.13
  intl: any
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  socket_io_client: ^2.0.3+1
  file_picker: ^5.3.3
  stringee_flutter_plugin:
    git:
      url: https://github.com/stringeecom/stringee_flutter_plugin.git
  device_info_plus: ^9.0.3
  photo_manager: ^2.7.1
  video_player: ^2.1.14
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  syncfusion_flutter_pdfviewer: ^20.4.54
  timelines: ^0.1.0
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  timeago: ^3.5.0
  textfield_tags: ^2.0.2
  flutter_screenutil: ^5.9.0
  dart_jsonwebtoken: ^2.12.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  syncfusion_flutter_charts: ^20.4.54
  flutter_stripe: ^9.5.0+1
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.2.4
  flutter_rating_bar: ^4.0.1
  chips_choice: ^3.0.1
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  logger: ^1.4.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ">=7.0.0 <8.0.0"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - assets/languages/
    - assets/image/
    - assets/anim/
    - assets/icons/bottom/
    - assets/icons/
    - assets/icons/common/
    - assets/icons/introduction/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Light.otf
