name: wflow
description: A Flutter application for student or freelancer and business connected, in addition the application provide solusion commit two hand when create contract for working
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_config_plus: ^1.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  dio: ^5.3.2
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  google_sign_in: ^6.1.4
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  local_auth: ^2.1.6
  flutter_flipperkit: ^0.0.29
  shared_preferences: ^2.2.0
  hydrated_bloc: ^9.1.2
  file_picker: ^5.3.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  badges: ^3.1.2
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  logger: ^2.0.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  freezed: ^2.4.2
flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    - assets/languages/
    - assets/anim/
    - assets/icons/bottom/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins_regular.ttf
          weight: 400
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
