version: 2.1
orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    executor:
      name: android/android-machine
    steps:
      - checkout

      - run:
          name: Assemble Release Build
          command: |
            cd android && ./gradlew assembleRelease && cd ..
workflows:
  sample:
    jobs:
      - build
