version: 2.1
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.2

jobs:
  build-release:
    executor:
      name: android/android-machine

    steps:
      - checkout
      - flutter/install
      - flutter/build:
          android: --release --no-shrink

      - run:
          name: Copy APK
          command: cp build/app/outputs/apk/release/app-release.apk app-release.apk

      - store_artifacts:
          path: app-release.apk
          destination: app-release.apk

workflows:
  version: 2
  build-android:
    jobs:
      - build-release
