version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
      - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk
          destination: app-release.apk

workflows:
  version: 2
  build:
    jobs:
      - build
