// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfoz8flhqizZVsDDvtlimWK6mf75qqUus',
    appId: '1:1077579337878:android:11565aa5fc04f9faec32b7',
    messagingSenderId: '1077579337878',
    projectId: 'wflow-35849',
    storageBucket: 'wflow-35849.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpEhNY8cMGrrbtNyGTRtMukLSJl7Wc_W0',
    appId: '1:1077579337878:ios:fa08f0b731c98645ec32b7',
    messagingSenderId: '1077579337878',
    projectId: 'wflow-35849',
    storageBucket: 'wflow-35849.appspot.com',
    androidClientId: '1077579337878-gt7901c4kt2k39h9m2lv71jcmb35furk.apps.googleusercontent.com',
    iosClientId: '1077579337878-qg9hklc7k7015l28qgpodq1uiilh3iqs.apps.googleusercontent.com',
    iosBundleId: 'com.flow.wflow',
  );
}
